import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { TemplateLibrary } from '@incitio/schema';
import { validateTemplate } from '../geometry.js';

const PATH = fileURLToPath(new URL('../../../../data/templates/mined.json', import.meta.url));

// The mined library is generated by the Python sidecar, so it is checked
// in as data and asserted here rather than trusted: bad geometry from the
// miner would surface as silently ugly pages, not as a crash.
describe.runIf(existsSync(PATH))('mined template library', () => {
  const library = TemplateLibrary.parse(JSON.parse(readFileSync(PATH, 'utf8')));

  it('parses against the schema', () => {
    expect(library.templates.length).toBeGreaterThan(0);
  });

  it('has no overlapping or out-of-grid slots in any template', () => {
    const broken = library.templates
      .map((t) => ({ id: t.id, errors: validateTemplate(t) }))
      .filter((r) => r.errors.length > 0);
    expect(broken).toEqual([]);
  });

  it('gives every template a unique id', () => {
    const ids = library.templates.map((t) => t.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('records mined provenance pointing at a source page', () => {
    for (const template of library.templates) {
      expect(template.provenance.source).toBe('mined');
      expect(template.provenance.catalogId).not.toBe('');
    }
  });

  it('covers a useful spread of page densities', () => {
    const counts = new Set(library.templates.map((t) => t.slots.length));
    expect(counts.size).toBeGreaterThanOrEqual(5);
  });

  it('only promotes into strictly larger slots', () => {
    for (const template of library.templates) {
      const byId = new Map(template.slots.map((s) => [s.id, s]));
      for (const slot of template.slots) {
        for (const targetId of slot.promotesTo) {
          const target = byId.get(targetId)!;
          expect(target.w * target.h).toBeGreaterThan(slot.w * slot.h);
        }
      }
    }
  });
});
